/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quadraticEc;

/**
 *
 * @author cedbo
 */
public class UIecuation extends javax.swing.JFrame {

    /**
     * Creates new form UIecuation
     */
    public UIecuation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitleEc = new javax.swing.JLabel();
        lbA = new javax.swing.JLabel();
        lbB = new javax.swing.JLabel();
        lbC = new javax.swing.JLabel();
        inputA = new javax.swing.JTextField();
        inputB = new javax.swing.JTextField();
        inputC = new javax.swing.JTextField();
        lbEc = new javax.swing.JLabel();
        inputEc = new javax.swing.JTextField();
        lbX1 = new javax.swing.JLabel();
        lbX2 = new javax.swing.JLabel();
        inputX1 = new javax.swing.JTextField();
        inputX2 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ecuacion cuadratica");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitleEc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitleEc.setText("ECUACION CUADRATICA");
        jPanel1.add(lbTitleEc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 300, -1));

        lbA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbA.setText("a:");
        jPanel1.add(lbA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        lbB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbB.setText("b:");
        jPanel1.add(lbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        lbC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbC.setText("c:");
        jPanel1.add(lbC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        inputA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAActionPerformed(evt);
            }
        });
        jPanel1.add(inputA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 110, -1));
        jPanel1.add(inputB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 110, -1));
        jPanel1.add(inputC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 110, -1));

        lbEc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEc.setText("ECUACION:");
        jPanel1.add(lbEc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        inputEc.setEnabled(false);
        inputEc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEcActionPerformed(evt);
            }
        });
        jPanel1.add(inputEc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 400, -1));

        lbX1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbX1.setText("X1:");
        jPanel1.add(lbX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lbX2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbX2.setText("X2:");
        jPanel1.add(lbX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        inputX1.setEnabled(false);
        inputX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputX1ActionPerformed(evt);
            }
        });
        jPanel1.add(inputX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, -1));

        inputX2.setEnabled(false);
        inputX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputX2ActionPerformed(evt);
            }
        });
        jPanel1.add(inputX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 150, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAActionPerformed

    private void inputEcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEcActionPerformed

    private void inputX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputX2ActionPerformed

    private void inputX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputX1ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(inputA.getText());
        double b = Double.parseDouble(inputB.getText());
        double c = Double.parseDouble(inputC.getText());
        QuadraticEcuation ecuation = new QuadraticEcuation(a, b, c);
        inputEc.setText(a + "x^2 + " + b + "x + " + c);
        inputX1.setText(ecuation.getX1());
        inputX2.setText(ecuation.getX2());

    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIecuation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIecuation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIecuation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIecuation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIecuation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JTextField inputA;
    private javax.swing.JTextField inputB;
    private javax.swing.JTextField inputC;
    private javax.swing.JTextField inputEc;
    private javax.swing.JTextField inputX1;
    private javax.swing.JTextField inputX2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbA;
    private javax.swing.JLabel lbB;
    private javax.swing.JLabel lbC;
    private javax.swing.JLabel lbEc;
    private javax.swing.JLabel lbTitleEc;
    private javax.swing.JLabel lbX1;
    private javax.swing.JLabel lbX2;
    // End of variables declaration//GEN-END:variables
}
