/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import figuras.*;
import java.awt.Color;

/**
 *
 * @author cedbo
 */
public class UIfiguras extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public UIfiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        panelOptCirculo = new javax.swing.JPanel();
        lbCirculo = new javax.swing.JLabel();
        panelOptCuadrado = new javax.swing.JPanel();
        lbCuadrado = new javax.swing.JLabel();
        panelOptTriangulo = new javax.swing.JPanel();
        lbTriangulo = new javax.swing.JLabel();
        panelOptRectangulo = new javax.swing.JPanel();
        lbRectangulo = new javax.swing.JLabel();
        panelOptRombo = new javax.swing.JPanel();
        lbRombo = new javax.swing.JLabel();
        panelOptTrapecio = new javax.swing.JPanel();
        lbTrapecio = new javax.swing.JLabel();
        icoFiguras = new javax.swing.JLabel();
        lbFiguras = new javax.swing.JLabel();
        panelTabs = new javax.swing.JTabbedPane();
        tabCirculo = new javax.swing.JPanel();
        lbTitleCirculo = new javax.swing.JLabel();
        lbRadioCirculo = new javax.swing.JLabel();
        inputRadio = new javax.swing.JTextField();
        btnCalcularCirculo = new javax.swing.JButton();
        lbPerimetroCirculo = new javax.swing.JLabel();
        lbAreaCirculo = new javax.swing.JLabel();
        inputPerCirculo = new javax.swing.JTextField();
        inputAreaCirculo = new javax.swing.JTextField();
        tabCuadrado = new javax.swing.JPanel();
        lbTitleCuadrado = new javax.swing.JLabel();
        lbLadoCuadrado = new javax.swing.JLabel();
        inputLadoCuadrado = new javax.swing.JTextField();
        btnCalcularCuadrado = new javax.swing.JButton();
        lbPerCuadrado = new javax.swing.JLabel();
        inputPerCuadrado = new javax.swing.JTextField();
        lbAreaCuadrado = new javax.swing.JLabel();
        inputAreaCuadrado = new javax.swing.JTextField();
        tabTriangulo = new javax.swing.JPanel();
        lbTitleTriang = new javax.swing.JLabel();
        lbAlturaTriang = new javax.swing.JLabel();
        inputAltTriang = new javax.swing.JTextField();
        lbBaseTriang = new javax.swing.JLabel();
        inputBaseTriang = new javax.swing.JTextField();
        btnCalculaTriang = new javax.swing.JButton();
        lbPerTriang = new javax.swing.JLabel();
        inputPerTriang = new javax.swing.JTextField();
        lbAreaTriang = new javax.swing.JLabel();
        inputAreaTriang = new javax.swing.JTextField();
        lbTipoTriang = new javax.swing.JLabel();
        inputTipoTriang = new javax.swing.JTextField();
        tabRectangulo = new javax.swing.JPanel();
        lbTitleRect = new javax.swing.JLabel();
        lbAlturaRect = new javax.swing.JLabel();
        inputAlturaRect = new javax.swing.JTextField();
        lbBaseRect = new javax.swing.JLabel();
        inputBaseRect = new javax.swing.JTextField();
        btnCalcularRect = new javax.swing.JButton();
        lbAreaRect = new javax.swing.JLabel();
        inputPerRect = new javax.swing.JTextField();
        lbPerRect = new javax.swing.JLabel();
        inputAreaRect = new javax.swing.JTextField();
        tabRombo = new javax.swing.JPanel();
        lbTitleRombo = new javax.swing.JLabel();
        lbDM = new javax.swing.JLabel();
        inputDM = new javax.swing.JTextField();
        lbDm = new javax.swing.JLabel();
        inputDm = new javax.swing.JTextField();
        btnCalculaRombo = new javax.swing.JButton();
        lbPerRombo = new javax.swing.JLabel();
        inputPerRombo = new javax.swing.JTextField();
        lbAreaRombo = new javax.swing.JLabel();
        inputAreaRombo = new javax.swing.JTextField();
        tabTrapecio = new javax.swing.JPanel();
        lbTitleTrapecio = new javax.swing.JLabel();
        lbBM = new javax.swing.JLabel();
        inputBM = new javax.swing.JTextField();
        lbBm = new javax.swing.JLabel();
        inputBm = new javax.swing.JTextField();
        btnCalcularTrap = new javax.swing.JButton();
        lbPerTrap = new javax.swing.JLabel();
        inputPerTrap = new javax.swing.JTextField();
        lbAreaTrap = new javax.swing.JLabel();
        inputAreaTrap = new javax.swing.JTextField();
        lbAltTrap = new javax.swing.JLabel();
        inputAltTrap = new javax.swing.JTextField();
        bannerPanel = new javax.swing.JPanel();
        imgFiguras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Figuras");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(252, 247, 248));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSidebar.setBackground(new java.awt.Color(78, 128, 152));
        panelSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOptCirculo.setBackground(new java.awt.Color(78, 128, 152));
        panelOptCirculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptCirculo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelOptCirculoMouseMoved(evt);
            }
        });
        panelOptCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOptCirculoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOptCirculoMouseExited(evt);
            }
        });
        panelOptCirculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCirculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCirculo.setForeground(new java.awt.Color(255, 255, 255));
        lbCirculo.setText("Circulo");
        panelOptCirculo.add(lbCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        panelSidebar.add(panelOptCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 50));

        panelOptCuadrado.setBackground(new java.awt.Color(78, 128, 152));
        panelOptCuadrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptCuadrado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelOptCuadradoMouseMoved(evt);
            }
        });
        panelOptCuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOptCuadradoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOptCuadradoMouseExited(evt);
            }
        });
        panelOptCuadrado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCuadrado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCuadrado.setForeground(new java.awt.Color(255, 255, 255));
        lbCuadrado.setText("Cuadrado");
        panelOptCuadrado.add(lbCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        panelSidebar.add(panelOptCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 50));

        panelOptTriangulo.setBackground(new java.awt.Color(78, 128, 152));
        panelOptTriangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptTriangulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelOptTrianguloMouseMoved(evt);
            }
        });
        panelOptTriangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOptTrianguloMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOptTrianguloMouseExited(evt);
            }
        });
        panelOptTriangulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTriangulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTriangulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTriangulo.setText("Triangulo");
        panelOptTriangulo.add(lbTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        panelSidebar.add(panelOptTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        panelOptRectangulo.setBackground(new java.awt.Color(78, 128, 152));
        panelOptRectangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptRectangulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelOptRectanguloMouseMoved(evt);
            }
        });
        panelOptRectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOptRectanguloMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOptRectanguloMouseExited(evt);
            }
        });
        panelOptRectangulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRectangulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbRectangulo.setForeground(new java.awt.Color(255, 255, 255));
        lbRectangulo.setText("Rectangulo");
        panelOptRectangulo.add(lbRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        panelSidebar.add(panelOptRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 50));

        panelOptRombo.setBackground(new java.awt.Color(78, 128, 152));
        panelOptRombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptRombo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelOptRomboMouseMoved(evt);
            }
        });
        panelOptRombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOptRomboMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOptRomboMouseExited(evt);
            }
        });
        panelOptRombo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRombo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbRombo.setForeground(new java.awt.Color(255, 255, 255));
        lbRombo.setText("Rombo");
        panelOptRombo.add(lbRombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        panelSidebar.add(panelOptRombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 50));

        panelOptTrapecio.setBackground(new java.awt.Color(78, 128, 152));
        panelOptTrapecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptTrapecio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelOptTrapecioMouseMoved(evt);
            }
        });
        panelOptTrapecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOptTrapecioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOptTrapecioMouseExited(evt);
            }
        });
        panelOptTrapecio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTrapecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTrapecio.setForeground(new java.awt.Color(255, 255, 255));
        lbTrapecio.setText("Trapecio");
        panelOptTrapecio.add(lbTrapecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        panelSidebar.add(panelOptTrapecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 50));

        icoFiguras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/banner2.png"))); // NOI18N
        panelSidebar.add(icoFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 60));

        lbFiguras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbFiguras.setForeground(new java.awt.Color(255, 255, 255));
        lbFiguras.setText("FIGURAS");
        panelSidebar.add(lbFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        getContentPane().add(panelSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        panelTabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelTabs.setOpaque(true);

        tabCirculo.setBackground(new java.awt.Color(252, 247, 248));

        lbTitleCirculo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbTitleCirculo.setForeground(new java.awt.Color(78, 128, 152));
        lbTitleCirculo.setText("CIRCULO");

        lbRadioCirculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbRadioCirculo.setForeground(new java.awt.Color(78, 128, 152));
        lbRadioCirculo.setText("RADIO:");

        btnCalcularCirculo.setText("Calcular");
        btnCalcularCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCirculoActionPerformed(evt);
            }
        });

        lbPerimetroCirculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPerimetroCirculo.setForeground(new java.awt.Color(78, 128, 152));
        lbPerimetroCirculo.setText("PERIMETRO DEL CIRCULO:");

        lbAreaCirculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAreaCirculo.setForeground(new java.awt.Color(78, 128, 152));
        lbAreaCirculo.setText("AREA DEL CIRCULO");

        inputPerCirculo.setText("0.");
        inputPerCirculo.setEnabled(false);
        inputPerCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPerCirculoActionPerformed(evt);
            }
        });

        inputAreaCirculo.setText("0.");
        inputAreaCirculo.setEnabled(false);
        inputAreaCirculo.setName(""); // NOI18N

        javax.swing.GroupLayout tabCirculoLayout = new javax.swing.GroupLayout(tabCirculo);
        tabCirculo.setLayout(tabCirculoLayout);
        tabCirculoLayout.setHorizontalGroup(
            tabCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCirculoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(tabCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAreaCirculo)
                    .addComponent(lbPerimetroCirculo)
                    .addGroup(tabCirculoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbTitleCirculo))
                    .addComponent(inputRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(btnCalcularCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPerCirculo)
                    .addComponent(inputAreaCirculo)
                    .addComponent(lbRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        tabCirculoLayout.setVerticalGroup(
            tabCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCirculoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbTitleCirculo)
                .addGap(18, 18, 18)
                .addComponent(lbRadioCirculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcularCirculo)
                .addGap(33, 33, 33)
                .addComponent(lbPerimetroCirculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputPerCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lbAreaCirculo)
                .addGap(18, 18, 18)
                .addComponent(inputAreaCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        panelTabs.addTab("tab1", tabCirculo);

        tabCuadrado.setBackground(new java.awt.Color(252, 247, 248));

        lbTitleCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbTitleCuadrado.setForeground(new java.awt.Color(78, 128, 152));
        lbTitleCuadrado.setText("CUADRADO");

        lbLadoCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLadoCuadrado.setForeground(new java.awt.Color(78, 128, 152));
        lbLadoCuadrado.setText("LADO:");

        inputLadoCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLadoCuadradoActionPerformed(evt);
            }
        });

        btnCalcularCuadrado.setText("Calcular");
        btnCalcularCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCuadradoActionPerformed(evt);
            }
        });

        lbPerCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPerCuadrado.setForeground(new java.awt.Color(78, 128, 152));
        lbPerCuadrado.setText("PERIMETRO DEL CUADRADO:");

        inputPerCuadrado.setText("0.");
        inputPerCuadrado.setEnabled(false);

        lbAreaCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAreaCuadrado.setForeground(new java.awt.Color(78, 128, 152));
        lbAreaCuadrado.setText("AREA DEL CUADRADO:");

        inputAreaCuadrado.setText("0.");
        inputAreaCuadrado.setEnabled(false);

        javax.swing.GroupLayout tabCuadradoLayout = new javax.swing.GroupLayout(tabCuadrado);
        tabCuadrado.setLayout(tabCuadradoLayout);
        tabCuadradoLayout.setHorizontalGroup(
            tabCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCuadradoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(tabCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAreaCuadrado)
                    .addComponent(lbPerCuadrado)
                    .addComponent(btnCalcularCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputLadoCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(lbLadoCuadrado)
                    .addComponent(lbTitleCuadrado)
                    .addComponent(inputPerCuadrado)
                    .addComponent(inputAreaCuadrado))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        tabCuadradoLayout.setVerticalGroup(
            tabCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCuadradoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbTitleCuadrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputLadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcularCuadrado)
                .addGap(42, 42, 42)
                .addComponent(lbPerCuadrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputPerCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAreaCuadrado)
                .addGap(18, 18, 18)
                .addComponent(inputAreaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        panelTabs.addTab("tab2", tabCuadrado);

        tabTriangulo.setBackground(new java.awt.Color(252, 247, 248));

        lbTitleTriang.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbTitleTriang.setForeground(new java.awt.Color(78, 128, 152));
        lbTitleTriang.setText("TRIANGULO");

        lbAlturaTriang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAlturaTriang.setForeground(new java.awt.Color(78, 128, 152));
        lbAlturaTriang.setText("ALTURA:");

        inputAltTriang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAltTriangActionPerformed(evt);
            }
        });

        lbBaseTriang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBaseTriang.setForeground(new java.awt.Color(78, 128, 152));
        lbBaseTriang.setText("BASE:");

        btnCalculaTriang.setText("Calcular");
        btnCalculaTriang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaTriangActionPerformed(evt);
            }
        });

        lbPerTriang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPerTriang.setForeground(new java.awt.Color(78, 128, 152));
        lbPerTriang.setText("PERIMETRO DEL TRIANGULO:");

        inputPerTriang.setText("0.");
        inputPerTriang.setEnabled(false);

        lbAreaTriang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAreaTriang.setForeground(new java.awt.Color(78, 128, 152));
        lbAreaTriang.setText("AREA DEL TRIANGULO:");

        inputAreaTriang.setText("0.");
        inputAreaTriang.setEnabled(false);

        lbTipoTriang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTipoTriang.setForeground(new java.awt.Color(78, 128, 152));
        lbTipoTriang.setText("TIPO DE TRIANGULO:");

        inputTipoTriang.setEditable(false);
        inputTipoTriang.setBackground(new java.awt.Color(255, 255, 255));
        inputTipoTriang.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        inputTipoTriang.setSelectionColor(new java.awt.Color(255, 255, 255));
        inputTipoTriang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipoTriangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabTrianguloLayout = new javax.swing.GroupLayout(tabTriangulo);
        tabTriangulo.setLayout(tabTrianguloLayout);
        tabTrianguloLayout.setHorizontalGroup(
            tabTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTrianguloLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(tabTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbPerTriang)
                    .addGroup(tabTrianguloLayout.createSequentialGroup()
                        .addComponent(lbTipoTriang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputTipoTriang))
                    .addComponent(inputAreaTriang, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAreaTriang)
                    .addComponent(btnCalculaTriang, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBaseTriang, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBaseTriang)
                    .addComponent(inputAltTriang, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAlturaTriang)
                    .addComponent(lbTitleTriang)
                    .addComponent(inputPerTriang, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        tabTrianguloLayout.setVerticalGroup(
            tabTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTrianguloLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbTitleTriang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAlturaTriang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAltTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBaseTriang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputBaseTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalculaTriang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPerTriang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPerTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAreaTriang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAreaTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoTriang)
                    .addComponent(inputTipoTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelTabs.addTab("tab3", tabTriangulo);

        tabRectangulo.setBackground(new java.awt.Color(252, 247, 248));

        lbTitleRect.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbTitleRect.setForeground(new java.awt.Color(78, 128, 152));
        lbTitleRect.setText("RECTANGULO");

        lbAlturaRect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAlturaRect.setForeground(new java.awt.Color(78, 128, 152));
        lbAlturaRect.setText("ALTURA:");

        lbBaseRect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBaseRect.setForeground(new java.awt.Color(78, 128, 152));
        lbBaseRect.setText("BASE:");

        inputBaseRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBaseRectActionPerformed(evt);
            }
        });

        btnCalcularRect.setText("Calcular");
        btnCalcularRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRectActionPerformed(evt);
            }
        });

        lbAreaRect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAreaRect.setForeground(new java.awt.Color(78, 128, 152));
        lbAreaRect.setText("PERIMETRO DEL RECTANGULO:");

        inputPerRect.setText("0.");
        inputPerRect.setEnabled(false);
        inputPerRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPerRectActionPerformed(evt);
            }
        });

        lbPerRect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPerRect.setForeground(new java.awt.Color(78, 128, 152));
        lbPerRect.setText("AREA DEL RECTANGULO:");

        inputAreaRect.setText("0.");
        inputAreaRect.setEnabled(false);

        javax.swing.GroupLayout tabRectanguloLayout = new javax.swing.GroupLayout(tabRectangulo);
        tabRectangulo.setLayout(tabRectanguloLayout);
        tabRectanguloLayout.setHorizontalGroup(
            tabRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRectanguloLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(tabRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbPerRect)
                    .addComponent(lbAreaRect)
                    .addComponent(btnCalcularRect, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBaseRect)
                    .addComponent(lbAlturaRect)
                    .addComponent(lbTitleRect)
                    .addComponent(inputAlturaRect, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBaseRect, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPerRect, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAreaRect, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        tabRectanguloLayout.setVerticalGroup(
            tabRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRectanguloLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbTitleRect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAlturaRect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAlturaRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbBaseRect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputBaseRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcularRect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAreaRect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPerRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPerRect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAreaRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        panelTabs.addTab("tab4", tabRectangulo);

        tabRombo.setBackground(new java.awt.Color(252, 247, 248));

        lbTitleRombo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbTitleRombo.setForeground(new java.awt.Color(78, 128, 152));
        lbTitleRombo.setText("ROMBO");

        lbDM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDM.setForeground(new java.awt.Color(78, 128, 152));
        lbDM.setText("DIAGONAL MAYOR:");

        inputDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDMActionPerformed(evt);
            }
        });

        lbDm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDm.setForeground(new java.awt.Color(78, 128, 152));
        lbDm.setText("DIAGONAL MENOR:");

        inputDm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDmActionPerformed(evt);
            }
        });

        btnCalculaRombo.setText("Calcular");
        btnCalculaRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaRomboActionPerformed(evt);
            }
        });

        lbPerRombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPerRombo.setForeground(new java.awt.Color(78, 128, 152));
        lbPerRombo.setText("PERIMETRO DEL ROMBO:");

        inputPerRombo.setText("0.");
        inputPerRombo.setEnabled(false);
        inputPerRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPerRomboActionPerformed(evt);
            }
        });

        lbAreaRombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAreaRombo.setForeground(new java.awt.Color(78, 128, 152));
        lbAreaRombo.setText("AREA DEL ROMBO:");

        inputAreaRombo.setText("0.");
        inputAreaRombo.setEnabled(false);

        javax.swing.GroupLayout tabRomboLayout = new javax.swing.GroupLayout(tabRombo);
        tabRombo.setLayout(tabRomboLayout);
        tabRomboLayout.setHorizontalGroup(
            tabRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRomboLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(tabRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAreaRombo)
                    .addComponent(lbPerRombo)
                    .addComponent(inputDM)
                    .addComponent(btnCalculaRombo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDm)
                    .addComponent(lbDM)
                    .addComponent(lbTitleRombo)
                    .addComponent(inputAreaRombo, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(inputPerRombo)
                    .addComponent(inputDm))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        tabRomboLayout.setVerticalGroup(
            tabRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRomboLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbTitleRombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculaRombo)
                .addGap(18, 18, 18)
                .addComponent(lbPerRombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPerRombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAreaRombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAreaRombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        panelTabs.addTab("tab5", tabRombo);

        tabTrapecio.setBackground(new java.awt.Color(252, 247, 248));
        tabTrapecio.setEnabled(false);

        lbTitleTrapecio.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbTitleTrapecio.setForeground(new java.awt.Color(78, 128, 152));
        lbTitleTrapecio.setText("TRAPECIO");

        lbBM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBM.setForeground(new java.awt.Color(78, 128, 152));
        lbBM.setText("BASE MAYOR:");

        lbBm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBm.setForeground(new java.awt.Color(78, 128, 152));
        lbBm.setText("BASE MENOR:");

        btnCalcularTrap.setText("Calcular");
        btnCalcularTrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTrapActionPerformed(evt);
            }
        });

        lbPerTrap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPerTrap.setForeground(new java.awt.Color(78, 128, 152));
        lbPerTrap.setText("PERIMETRO DEL TRAPECIO:");

        inputPerTrap.setText("0.");
        inputPerTrap.setEnabled(false);
        inputPerTrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPerTrapActionPerformed(evt);
            }
        });

        lbAreaTrap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAreaTrap.setForeground(new java.awt.Color(78, 128, 152));
        lbAreaTrap.setText("AREA DEL TRAPECIO:");

        inputAreaTrap.setText("0.");
        inputAreaTrap.setEnabled(false);
        inputAreaTrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAreaTrapActionPerformed(evt);
            }
        });

        lbAltTrap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAltTrap.setForeground(new java.awt.Color(78, 128, 152));
        lbAltTrap.setText("ALTURA:");

        javax.swing.GroupLayout tabTrapecioLayout = new javax.swing.GroupLayout(tabTrapecio);
        tabTrapecio.setLayout(tabTrapecioLayout);
        tabTrapecioLayout.setHorizontalGroup(
            tabTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTrapecioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tabTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcularTrap, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerTrap)
                    .addComponent(lbAltTrap)
                    .addComponent(inputAreaTrap, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAreaTrap)
                    .addComponent(inputPerTrap, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAltTrap, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBm, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBm)
                    .addComponent(inputBM, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBM)
                    .addComponent(lbTitleTrapecio))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        tabTrapecioLayout.setVerticalGroup(
            tabTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTrapecioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTitleTrapecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputBm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAltTrap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAltTrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcularTrap)
                .addGap(4, 4, 4)
                .addComponent(lbPerTrap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPerTrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAreaTrap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAreaTrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelTabs.addTab("tab6", tabTrapecio);

        getContentPane().add(panelTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -40, 500, 440));
        panelTabs.getAccessibleContext().setAccessibleDescription("");

        bannerPanel.setBackground(new java.awt.Color(252, 247, 248));
        bannerPanel.setPreferredSize(new java.awt.Dimension(504, 407));

        imgFiguras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/banner.png"))); // NOI18N

        javax.swing.GroupLayout bannerPanelLayout = new javax.swing.GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerPanelLayout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(imgFiguras)
                .addGap(21, 21, 21))
        );
        bannerPanelLayout.setVerticalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(imgFiguras)
                .addContainerGap())
        );

        getContentPane().add(bannerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 500, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCirculoActionPerformed
        // TODO add your handling code here:
        double radio = Double.parseDouble(inputRadio.getText());
        Circulo circulo = new Circulo(radio);
        inputPerCirculo.setText(String.valueOf(circulo.calcularPerimetro()));
        inputAreaCirculo.setText(String.valueOf(circulo.calcularArea()));
    }//GEN-LAST:event_btnCalcularCirculoActionPerformed

    private void inputPerCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPerCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPerCirculoActionPerformed

    private void btnCalcularCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCuadradoActionPerformed
        // TODO add your handling code here:
        double lado = Double.parseDouble(inputLadoCuadrado.getText());
        Cuadrado cuadrado = new Cuadrado(lado);
        inputPerCuadrado.setText(String.valueOf(cuadrado.calcularPerimetro()));
        inputAreaCuadrado.setText(String.valueOf(cuadrado.calcularArea()));
    }//GEN-LAST:event_btnCalcularCuadradoActionPerformed

    private void inputLadoCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLadoCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLadoCuadradoActionPerformed

    private void btnCalcularRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRectActionPerformed
        // TODO add your handling code here:
        double altura = Double.parseDouble(inputAlturaRect.getText());
        double base = Double.parseDouble(inputBaseRect.getText());
        Rectangulo rectangulo = new Rectangulo(base, altura);
        inputPerRect.setText(String.valueOf(rectangulo.calcularPerimetro()));
        inputAreaRect.setText(String.valueOf(rectangulo.calcularArea()));

    }//GEN-LAST:event_btnCalcularRectActionPerformed

    private void inputBaseRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBaseRectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBaseRectActionPerformed

    private void panelOptCirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptCirculoMouseClicked
        // TODO add your handling code here:
        panelTabs.setSelectedIndex(0);
    }//GEN-LAST:event_panelOptCirculoMouseClicked

    private void panelOptCuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptCuadradoMouseClicked
        // TODO add your handling code here:
        panelTabs.setSelectedIndex(1);
    }//GEN-LAST:event_panelOptCuadradoMouseClicked

    private void panelOptTrianguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptTrianguloMouseClicked
        // TODO add your handling code here:
        panelTabs.setSelectedIndex(2);
    }//GEN-LAST:event_panelOptTrianguloMouseClicked

    private void panelOptRomboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptRomboMouseClicked
        // TODO add your handling code here:
        panelTabs.setSelectedIndex(4);
    }//GEN-LAST:event_panelOptRomboMouseClicked

    private void panelOptRectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptRectanguloMouseClicked
        // TODO add your handling code here:
        panelTabs.setSelectedIndex(3);
    }//GEN-LAST:event_panelOptRectanguloMouseClicked

    private void panelOptTrapecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptTrapecioMouseClicked
        // TODO add your handling code here:
        panelTabs.setSelectedIndex(5);
    }//GEN-LAST:event_panelOptTrapecioMouseClicked

    private void inputDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDMActionPerformed

    private void inputDmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDmActionPerformed

    private void inputPerRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPerRomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPerRomboActionPerformed

    private void inputPerRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPerRectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPerRectActionPerformed

    private void btnCalculaRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaRomboActionPerformed
        // TODO add your handling code here:
        double dMayor = Double.parseDouble(inputDM.getText());
        double dMenor = Double.parseDouble(inputDm.getText());
        Rombo rombo = new Rombo(dMayor, dMenor);
        inputPerRombo.setText(String.valueOf(rombo.calcularPerimetro()));
        inputAreaRombo.setText(String.valueOf(rombo.calcularArea()));
    }//GEN-LAST:event_btnCalculaRomboActionPerformed

    private void inputTipoTriangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipoTriangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipoTriangActionPerformed

    private void inputAltTriangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAltTriangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAltTriangActionPerformed

    private void btnCalculaTriangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaTriangActionPerformed
        // TODO add your handling code here:
        double altura = Double.parseDouble(inputAltTriang.getText());
        double base = Double.parseDouble(inputBaseTriang.getText());
        Triangulo triangulo = new Triangulo(altura, base);
        inputAreaTriang.setText(String.valueOf(triangulo.calcularArea()));
        inputPerTriang.setText(String.valueOf(triangulo.calcularPerimetro()));
        inputTipoTriang.setText(triangulo.determinarTipoTriangulo());

    }//GEN-LAST:event_btnCalculaTriangActionPerformed

    private void btnCalcularTrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTrapActionPerformed
        // TODO add your handling code here:
        double altura = Double.parseDouble(inputAltTrap.getText());
        double bMayor = Double.parseDouble(inputBM.getText());
        double bMenor = Double.parseDouble(inputBm.getText());
        Trapecio trapecio = new Trapecio(bMenor, bMayor, altura);
        inputPerTrap.setText(String.valueOf(trapecio.calcularPerimetro()));
        inputAreaTrap.setText(String.valueOf(trapecio.calcularArea()));
    }//GEN-LAST:event_btnCalcularTrapActionPerformed

    private void inputPerTrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPerTrapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPerTrapActionPerformed

    private void inputAreaTrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAreaTrapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAreaTrapActionPerformed

    private void panelOptCirculoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptCirculoMouseMoved
        // TODO add your handling code here:
        panelOptCirculo.setBackground(new Color(137, 175, 194));
    }//GEN-LAST:event_panelOptCirculoMouseMoved

    private void panelOptCirculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptCirculoMouseExited
        // TODO add your handling code here:
        panelOptCirculo.setBackground(new Color(78, 128, 152));
    }//GEN-LAST:event_panelOptCirculoMouseExited

    private void panelOptCuadradoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptCuadradoMouseMoved
        // TODO add your handling code here:
        panelOptCuadrado.setBackground(new Color(137, 175, 194));
    }//GEN-LAST:event_panelOptCuadradoMouseMoved

    private void panelOptCuadradoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptCuadradoMouseExited
        // TODO add your handling code here:
        panelOptCuadrado.setBackground(new Color(78, 128, 152));
    }//GEN-LAST:event_panelOptCuadradoMouseExited

    private void panelOptTrianguloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptTrianguloMouseMoved
        // TODO add your handling code here:
        panelOptTriangulo.setBackground(new Color(137, 175, 194));
    }//GEN-LAST:event_panelOptTrianguloMouseMoved

    private void panelOptTrianguloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptTrianguloMouseExited
        // TODO add your handling code here:
        panelOptTriangulo.setBackground(new Color(78, 128, 152));
    }//GEN-LAST:event_panelOptTrianguloMouseExited

    private void panelOptRomboMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptRomboMouseMoved
        // TODO add your handling code here:
        panelOptRombo.setBackground(new Color(137, 175, 194));
    }//GEN-LAST:event_panelOptRomboMouseMoved

    private void panelOptRomboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptRomboMouseExited
        // TODO add your handling code here:
        panelOptRombo.setBackground(new Color(78, 128, 152));
    }//GEN-LAST:event_panelOptRomboMouseExited

    private void panelOptRectanguloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptRectanguloMouseMoved
        // TODO add your handling code here:
        panelOptRectangulo.setBackground(new Color(137, 175, 194));
    }//GEN-LAST:event_panelOptRectanguloMouseMoved

    private void panelOptRectanguloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptRectanguloMouseExited
        // TODO add your handling code here:
        panelOptRectangulo.setBackground(new Color(78, 128, 152));
    }//GEN-LAST:event_panelOptRectanguloMouseExited

    private void panelOptTrapecioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptTrapecioMouseMoved
        // TODO add your handling code here:
        panelOptTrapecio.setBackground(new Color(137, 175, 194));
    }//GEN-LAST:event_panelOptTrapecioMouseMoved

    private void panelOptTrapecioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOptTrapecioMouseExited
        // TODO add your handling code here:
        panelOptTrapecio.setBackground(new Color(78, 128, 152));
    }//GEN-LAST:event_panelOptTrapecioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIfiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIfiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIfiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIfiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIfiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JButton btnCalculaRombo;
    private javax.swing.JButton btnCalculaTriang;
    private javax.swing.JButton btnCalcularCirculo;
    private javax.swing.JButton btnCalcularCuadrado;
    private javax.swing.JButton btnCalcularRect;
    private javax.swing.JButton btnCalcularTrap;
    private javax.swing.JLabel icoFiguras;
    private javax.swing.JLabel imgFiguras;
    private javax.swing.JTextField inputAltTrap;
    private javax.swing.JTextField inputAltTriang;
    private javax.swing.JTextField inputAlturaRect;
    private javax.swing.JTextField inputAreaCirculo;
    private javax.swing.JTextField inputAreaCuadrado;
    private javax.swing.JTextField inputAreaRect;
    private javax.swing.JTextField inputAreaRombo;
    private javax.swing.JTextField inputAreaTrap;
    private javax.swing.JTextField inputAreaTriang;
    private javax.swing.JTextField inputBM;
    private javax.swing.JTextField inputBaseRect;
    private javax.swing.JTextField inputBaseTriang;
    private javax.swing.JTextField inputBm;
    private javax.swing.JTextField inputDM;
    private javax.swing.JTextField inputDm;
    private javax.swing.JTextField inputLadoCuadrado;
    private javax.swing.JTextField inputPerCirculo;
    private javax.swing.JTextField inputPerCuadrado;
    private javax.swing.JTextField inputPerRect;
    private javax.swing.JTextField inputPerRombo;
    private javax.swing.JTextField inputPerTrap;
    private javax.swing.JTextField inputPerTriang;
    private javax.swing.JTextField inputRadio;
    private javax.swing.JTextField inputTipoTriang;
    private javax.swing.JLabel lbAltTrap;
    private javax.swing.JLabel lbAlturaRect;
    private javax.swing.JLabel lbAlturaTriang;
    private javax.swing.JLabel lbAreaCirculo;
    private javax.swing.JLabel lbAreaCuadrado;
    private javax.swing.JLabel lbAreaRect;
    private javax.swing.JLabel lbAreaRombo;
    private javax.swing.JLabel lbAreaTrap;
    private javax.swing.JLabel lbAreaTriang;
    private javax.swing.JLabel lbBM;
    private javax.swing.JLabel lbBaseRect;
    private javax.swing.JLabel lbBaseTriang;
    private javax.swing.JLabel lbBm;
    private javax.swing.JLabel lbCirculo;
    private javax.swing.JLabel lbCuadrado;
    private javax.swing.JLabel lbDM;
    private javax.swing.JLabel lbDm;
    private javax.swing.JLabel lbFiguras;
    private javax.swing.JLabel lbLadoCuadrado;
    private javax.swing.JLabel lbPerCuadrado;
    private javax.swing.JLabel lbPerRect;
    private javax.swing.JLabel lbPerRombo;
    private javax.swing.JLabel lbPerTrap;
    private javax.swing.JLabel lbPerTriang;
    private javax.swing.JLabel lbPerimetroCirculo;
    private javax.swing.JLabel lbRadioCirculo;
    private javax.swing.JLabel lbRectangulo;
    private javax.swing.JLabel lbRombo;
    private javax.swing.JLabel lbTipoTriang;
    private javax.swing.JLabel lbTitleCirculo;
    private javax.swing.JLabel lbTitleCuadrado;
    private javax.swing.JLabel lbTitleRect;
    private javax.swing.JLabel lbTitleRombo;
    private javax.swing.JLabel lbTitleTrapecio;
    private javax.swing.JLabel lbTitleTriang;
    private javax.swing.JLabel lbTrapecio;
    private javax.swing.JLabel lbTriangulo;
    private javax.swing.JPanel panelOptCirculo;
    private javax.swing.JPanel panelOptCuadrado;
    private javax.swing.JPanel panelOptRectangulo;
    private javax.swing.JPanel panelOptRombo;
    private javax.swing.JPanel panelOptTrapecio;
    private javax.swing.JPanel panelOptTriangulo;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JTabbedPane panelTabs;
    private javax.swing.JPanel tabCirculo;
    private javax.swing.JPanel tabCuadrado;
    private javax.swing.JPanel tabRectangulo;
    private javax.swing.JPanel tabRombo;
    private javax.swing.JPanel tabTrapecio;
    private javax.swing.JPanel tabTriangulo;
    // End of variables declaration//GEN-END:variables
}
