/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package comparator;

/**
 *
 * @author cedbo
 */
public class UIcomparator extends javax.swing.JFrame {

    /**
     * Creates new form UIcomparator
     */
    public UIcomparator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitleComparar = new javax.swing.JLabel();
        inputA = new javax.swing.JTextField();
        lbA = new javax.swing.JLabel();
        inputB = new javax.swing.JTextField();
        lbB = new javax.swing.JLabel();
        btnComparar = new javax.swing.JButton();
        inputRespuesta = new javax.swing.JTextField();
        lbRespuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comparador");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitleComparar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTitleComparar.setText("COMPARAR NUMEROS");
        jPanel1.add(lbTitleComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        jPanel1.add(inputA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, -1));

        lbA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbA.setText("A:");
        jPanel1.add(lbA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel1.add(inputB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 160, -1));

        lbB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbB.setText("B:");
        jPanel1.add(lbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        btnComparar.setText("Comparar");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });
        jPanel1.add(btnComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, -1));

        inputRespuesta.setEnabled(false);
        jPanel1.add(inputRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 340, -1));

        lbRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbRespuesta.setText("RESPUESTA:");
        jPanel1.add(lbRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(inputA.getText());
        double b = Double.parseDouble(inputB.getText());
        Comparator comparador = new Comparator(a, b);
        inputRespuesta.setText(comparador.doComparation());
    }//GEN-LAST:event_btnCompararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIcomparator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIcomparator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIcomparator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIcomparator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIcomparator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComparar;
    private javax.swing.JTextField inputA;
    private javax.swing.JTextField inputB;
    private javax.swing.JTextField inputRespuesta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbA;
    private javax.swing.JLabel lbB;
    private javax.swing.JLabel lbRespuesta;
    private javax.swing.JLabel lbTitleComparar;
    // End of variables declaration//GEN-END:variables
}
